export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const REGISTER_USER = 'REGISTER_USER';
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';
